const config = require("../config");
const pg = require("./pg");

/**
 * ChatDbService - AI assistant chat metadata (RDS Postgres)
 * Single Responsibility: SQL persistence of chat metadata.
 *
 * Transcripts live in S3 (see services/chat-store.js); rows here hold the
 * snapshot's S3 *key* only — never presigned URLs (they expire).
 * Every query is scoped by user_id: cross-user access is impossible by
 * construction.
 */

/**
 * @returns {import('pg').Pool}
 */
function getPool() {
  if (!config.ASSISTANT_ENABLED) {
    throw new Error("AI assistant is not enabled (DATABASE_URL missing)");
  }
  return pg.getPool();
}

let schemaReady = null;

/**
 * Ensure schema exists (idempotent, mirrors migrations/001-assistant-chats.sql).
 * @returns {Promise<void>}
 */
function ensureSchema() {
  if (!schemaReady) {
    schemaReady = getPool().query(`
      CREATE TABLE IF NOT EXISTS assistant_chats (
        id              UUID PRIMARY KEY,
        user_id         TEXT NOT NULL,
        page_slug       TEXT NOT NULL,
        title           TEXT NOT NULL DEFAULT 'New chat',
        message_count   INT  NOT NULL DEFAULT 0,
        snapshot_s3_key TEXT NOT NULL,
        created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE INDEX IF NOT EXISTS idx_chats_user_page
        ON assistant_chats (user_id, page_slug, updated_at DESC);
    `).catch((err) => {
      schemaReady = null; // allow retry on next call
      throw err;
    });
  }
  return schemaReady;
}

/**
 * List a user's chats for a page, most recent first.
 * @param {string} userId
 * @param {string} slug
 * @returns {Promise<Array<{id, title, message_count, created_at, updated_at}>>}
 */
async function listChats(userId, slug) {
  await ensureSchema();
  const { rows } = await getPool().query(
    `SELECT id, title, message_count, created_at, updated_at
       FROM assistant_chats
      WHERE user_id = $1 AND page_slug = $2
      ORDER BY updated_at DESC
      LIMIT 100`,
    [userId, slug]
  );
  return rows;
}

/**
 * Create a chat row.
 * @param {string} id - UUID generated by the caller (used for the S3 key too)
 * @param {string} userId
 * @param {string} slug
 * @param {string} snapshotS3Key
 * @returns {Promise<{id: string}>}
 */
async function createChat(id, userId, slug, snapshotS3Key) {
  await ensureSchema();
  await getPool().query(
    `INSERT INTO assistant_chats (id, user_id, page_slug, snapshot_s3_key)
     VALUES ($1, $2, $3, $4)`,
    [id, userId, slug, snapshotS3Key]
  );
  return { id };
}

/**
 * Fetch a chat — ownership enforced in the WHERE clause.
 * @param {string} chatId
 * @param {string} userId
 * @returns {Promise<Object|null>}
 */
async function getChat(chatId, userId) {
  await ensureSchema();
  const { rows } = await getPool().query(
    `SELECT id, user_id, page_slug, title, message_count, snapshot_s3_key,
            created_at, updated_at
       FROM assistant_chats
      WHERE id = $1 AND user_id = $2`,
    [chatId, userId]
  );
  return rows[0] || null;
}

/**
 * Bump metadata after messages are appended.
 * @param {string} chatId
 * @param {string} userId
 * @param {number} addedCount
 * @param {string|null} title - set only if still the default
 * @returns {Promise<void>}
 */
async function touchChat(chatId, userId, addedCount, title) {
  await ensureSchema();
  await getPool().query(
    `UPDATE assistant_chats
        SET message_count = message_count + $3,
            updated_at = now(),
            title = CASE WHEN title = 'New chat' AND $4::text IS NOT NULL
                         THEN $4 ELSE title END
      WHERE id = $1 AND user_id = $2`,
    [chatId, userId, addedCount, title || null]
  );
}

/**
 * Delete a chat row (ownership enforced). Returns the deleted row or null.
 * @param {string} chatId
 * @param {string} userId
 * @returns {Promise<Object|null>}
 */
async function deleteChat(chatId, userId) {
  await ensureSchema();
  const { rows } = await getPool().query(
    `DELETE FROM assistant_chats
      WHERE id = $1 AND user_id = $2
      RETURNING id, snapshot_s3_key`,
    [chatId, userId]
  );
  return rows[0] || null;
}

module.exports = {
  listChats,
  createChat,
  getChat,
  touchChat,
  deleteChat,
};
